module.exports = {
    solutionCookie: [
        {
            "domain": ".geeksforgeeks.org",
            "expirationDate": 1681816119,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_fbp",
            "path": "/",
            "sameSite": "lax",
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "fb.1.1673975085228.1290134593"
        },
        {
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "httpOnly": false,
            "name": "gfgpromoparams",
            "path": "/",
            "sameSite": null,
            "secure": false,
            "session": true,
            "storeId": null,
            "value": "{\"utm_source\":\"practice\",\"utm_medium\":\"banner\",\"utm_campaign\":\"gfgweekly\"}"
        },
        {
            "domain": ".geeksforgeeks.org",
            "expirationDate": 1737111537,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_ga",
            "path": "/",
            "sameSite": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "GA1.1.297964024.1673975085"
        },
        {
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "httpOnly": true,
            "name": "authtoken",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": true,
            "session": true,
            "storeId": null,
            "value": "76854111cfff4e6c51c2a3ab6d98ea3a"
        },
        {
            "domain": ".geeksforgeeks.org",
            "expirationDate": 1705557713,
            "hostOnly": false,
            "httpOnly": false,
            "name": "gfg_id5_identity",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": null,
            "value": "5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9"
        },
        {
            "domain": ".geeksforgeeks.org",
            "expirationDate": 1681797713,
            "hostOnly": false,
            "httpOnly": true,
            "name": "gfguserName",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": null,
            "value": "pulkeetprg829%2FeyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvd3d3LmdlZWtzZm9yZ2Vla3Mub3JnXC8iLCJpYXQiOjE2NzQwMjE3MzQsImV4cCI6MTY4MTc5NzczNCwiaGFuZGxlIjoicHVsa2VldHByZzgyOSIsInV1aWQiOiI5MTQyYzIxZWEzNTA5NmRmN2MwNzRjNDY3MjAzZDQyMyIsInByb2ZpbGVVcmwiOiJodHRwczpcL1wvbWVkaWEuZ2Vla3Nmb3JnZWVrcy5vcmdcL2ltZy1wcmFjdGljZVwvdXNlcl93ZWItMTU5ODQzMzIyOC5zdmciLCJpbnN0aXR1dGVJZCI6MTMyNSwiaW5zdGl0dXRlTmFtZSI6IkRldmkgQWhpbHlhIFVuaXZlcnNpdHkgSW5kb3JlIiwibmFtZSI6IlB1bGtpdCBQcmFqYXBhdCIsImlzSW50ZXJlc3RTZWxlY3RlZCI6ZmFsc2UsInB1aWQiOiJ1bWlKU2RBejBDMD0iLCJwYSI6MX0.jwa-h3ZF2B9hBaU315NbtedwVZLBPCLvpmO4Dw470guVoSepSaIRLZyx1Rxno95eg9wxvJtV65p3jZihEuUDUNjo68kK_Iuldt7yDpWpJ_DqSBFDUJ8EvXxRz1S70XDUtGqXAZxAgOnT9PrnY4Q6vUoskhzYJ9c9PHNMGzXgHJ6W8NqdnHILts-u2PktHcvbXAZSGrHIZ9vhlylU8TkqD8iZdWU6SEIW45HKBI6GU9IQTh2gaAyvlc6gbtrBKEd5Ft4uiMS3-jfQCrNMw1bRJvbibKhuKLkqwTBrbbPXa0h4VOG-DX1tN9XM4WRgQ7nAnjiO_Uvh_-wqaepN-M73MA"
        },
        {
            "domain": ".geeksforgeeks.org",
            "expirationDate": 1689526971,
            "hostOnly": false,
            "httpOnly": false,
            "name": "g_state",
            "path": "/",
            "sameSite": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "{\"i_l\":0}"
        },
        {
            "domain": ".geeksforgeeks.org",
            "expirationDate": 1705557567,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_clck",
            "path": "/",
            "sameSite": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "1cq666i|1|f8d|0"
        },
        {
            "domain": ".geeksforgeeks.org",
            "expirationDate": 1737111540,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_ga_SZ454CLTZM",
            "path": "/",
            "sameSite": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "GS1.1.1674039531.7.1.1674039540.51.0.0"
        },
        {
            "domain": ".geeksforgeeks.org",
            "expirationDate": 1681751085,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_gcl_au",
            "path": "/",
            "sameSite": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "1.1.1030624026.1673975085.1742274257.1673975088.1673975153"
        },
        {
            "domain": ".geeksforgeeks.org",
            "expirationDate": 1674125937,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_gid",
            "path": "/",
            "sameSite": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "GA1.2.669168078.1673975085"
        },
        {
            "domain": "practice.geeksforgeeks.org",
            "expirationDate": 1705511427,
            "hostOnly": true,
            "httpOnly": false,
            "name": "geeksforgeeks_consent_status",
            "path": "/",
            "sameSite": "lax",
            "secure": true,
            "session": false,
            "storeId": null,
            "value": "dismiss"
        },
        {
            "domain": ".geeksforgeeks.org",
            "expirationDate": 1705557659,
            "hostOnly": false,
            "httpOnly": true,
            "name": "gfg_nluid",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": null,
            "value": "b80ad8b165ae6cd5e1719870491727ad"
        },
        {
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "httpOnly": false,
            "name": "http_referrer",
            "path": "/",
            "sameSite": null,
            "secure": false,
            "session": true,
            "storeId": null,
            "value": "\"https://practice.geeksforgeeks.org/problems/6eb51dc638ee1b936f38d1ab4b2f7062d4425463/1\""
        },
        {
            "domain": "practice.geeksforgeeks.org",
            "expirationDate": 1674061485,
            "hostOnly": true,
            "httpOnly": false,
            "name": "ln_or",
            "path": "/",
            "sameSite": null,
            "secure": false,
            "session": false,
            "storeId": null,
            "value": "eyIyNDM2OTcwIjoiZCJ9"
        }
    ]
}