module.exports = {
    tiklup1729Cookies: [
        {
            "name": "_ga",
            "value": "GA1.1.608757559.1665557146",
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "path": "/",
            "secure": false,
            "httpOnly": false,
            "sameSite": "no_restriction",
            "session": false,
            "firstPartyDomain": "",
            "partitionKey": null,
            "expirationDate": 1731516232,
            "storeId": null
        },
        {
            "name": "authtoken",
            "value": "660f63a7b63ad597c9295620af1ff910",
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "path": "/",
            "secure": true,
            "httpOnly": true,
            "sameSite": "no_restriction",
            "session": true,
            "firstPartyDomain": "",
            "partitionKey": null,
            "storeId": null
        },
        {
            "name": "gfg_id5_identity",
            "value": "5feceb66ffc86f38d952786c6d696c79c2dbc239dd4e91b46729d73a27fb57e9",
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "path": "/",
            "secure": true,
            "httpOnly": false,
            "sameSite": "no_restriction",
            "session": false,
            "firstPartyDomain": "",
            "partitionKey": null,
            "expirationDate": 1705577011,
            "storeId": null
        },
        {
            "name": "gfguserName",
            "value": "tiklup1729%2FeyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvd3d3LmdlZWtzZm9yZ2Vla3Mub3JnXC8iLCJpYXQiOjE2NzQwNDEwMzMsImV4cCI6MTY4MTgxNzAzMiwiaGFuZGxlIjoidGlrbHVwMTcyOSIsInV1aWQiOiI3NzEwZmEyN2Q3NDliNzY3MDIzNjM5ODYwOGRmYWI2MiIsInByb2ZpbGVVcmwiOiJodHRwczpcL1wvbWVkaWEuZ2Vla3Nmb3JnZWVrcy5vcmdcL2ltZy1wcmFjdGljZVwvdXNlcl93ZWItMTU5ODQzMzIyOC5zdmciLCJpbnN0aXR1dGVJZCI6MTc0MzgsImluc3RpdHV0ZU5hbWUiOiJJbmRpYW4gSW5zdGl0dXRlIG9mIFRlY2hub2xvZ3kgSmFtbXUiLCJuYW1lIjoiUHVsa2l0IiwiaXNJbnRlcmVzdFNlbGVjdGVkIjpmYWxzZSwicHVpZCI6InVXdU9SOTQyMWc9PSIsInBhIjoxfQ.PiyKCMPWIFGMIPw1BP8pOyI841aoL9DunkQvBQutqEJLOvnEi7bbam5m_j-H5wq28qD1u3mC-8YQn-I2U8LkkeBHeslMOoP_CBPf_DCohrJTCdjKegTnOcfKDE_bouhSHBhYTJKNiJnf3j9WC7tux7R_5fzFP5UL4uNqT32chQGZlGfuyWczGyHmuQ5VDdULJ66fNVGhIBRKoElaOGbCnhf7vOI68ni96FHAQFyMNexqAcZUfsWAWLnzlIfdG14cEtWlPd4Aa6O0xONnPAfXsWvkAsOh6ALg2_hYxm2zCunZ8Pnq3nh9Zo-JNqprkhh2CdShL3iECs1CmBmaUO2Apg",
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "path": "/",
            "secure": true,
            "httpOnly": true,
            "sameSite": "no_restriction",
            "session": false,
            "firstPartyDomain": "",
            "partitionKey": null,
            "expirationDate": 1681817010,
            "storeId": null
        },
        {
            "name": "g_state",
            "value": "{\"i_l\":0}",
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "path": "/",
            "secure": false,
            "httpOnly": false,
            "sameSite": "no_restriction",
            "session": false,
            "firstPartyDomain": "",
            "partitionKey": null,
            "expirationDate": 1689593009,
            "storeId": null
        },
        {
            "name": "_gaexp",
            "value": "GAX1.2.p1sb2BMPRbiAOVFdKkNm3w.19313.1",
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "path": "/",
            "secure": false,
            "httpOnly": false,
            "sameSite": "no_restriction",
            "session": false,
            "firstPartyDomain": "",
            "partitionKey": null,
            "expirationDate": 1668643200,
            "storeId": null
        },
        {
            "name": "g_csrf_token",
            "value": "f90d03038af90ef9",
            "domain": "practice.geeksforgeeks.org",
            "hostOnly": true,
            "path": "/",
            "secure": true,
            "httpOnly": false,
            "sameSite": "no_restriction",
            "session": false,
            "firstPartyDomain": "",
            "partitionKey": null,
            "expirationDate": 1674041309,
            "storeId": null
        },
        {
            "name": "_ga_DWCCJLKX3X",
            "value": "GS1.1.1668444232.2.1.1668444312.60.0.0",
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "path": "/",
            "secure": false,
            "httpOnly": false,
            "sameSite": "no_restriction",
            "session": false,
            "firstPartyDomain": "",
            "partitionKey": null,
            "expirationDate": 1731516312,
            "storeId": null
        },
        {
            "name": "_gcl_au",
            "value": "1.1.1100775001.1665557148",
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "path": "/",
            "secure": false,
            "httpOnly": false,
            "sameSite": "no_restriction",
            "session": false,
            "firstPartyDomain": "",
            "partitionKey": null,
            "expirationDate": 1673333148,
            "storeId": null
        },
        {
            "name": "AKA_A2",
            "value": "A",
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "path": "/",
            "secure": true,
            "httpOnly": true,
            "sameSite": "no_restriction",
            "session": false,
            "firstPartyDomain": "",
            "partitionKey": null,
            "expirationDate": 1673989747,
            "storeId": null
        },
        {
            "name": "gfg_nluid",
            "value": "93dde882c4015000f45b3795dcc2a489",
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "path": "/",
            "secure": true,
            "httpOnly": true,
            "sameSite": "no_restriction",
            "session": false,
            "firstPartyDomain": "",
            "partitionKey": null,
            "expirationDate": 1697093149,
            "storeId": null
        },
        {
            "name": "gfg_theme",
            "value": "gfgThemeDark",
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "path": "/",
            "secure": false,
            "httpOnly": false,
            "sameSite": "no_restriction",
            "session": false,
            "firstPartyDomain": "",
            "partitionKey": null,
            "expirationDate": 1704067201,
            "storeId": null
        },
        {
            "name": "http_referrer",
            "value": "\"https://practice.geeksforgeeks.org/\"",
            "domain": ".geeksforgeeks.org",
            "hostOnly": false,
            "path": "/",
            "secure": false,
            "httpOnly": false,
            "sameSite": "no_restriction",
            "session": true,
            "firstPartyDomain": "",
            "partitionKey": null,
            "storeId": null
        }
    ]
}