module.exports = [
    {
        "domain": ".geeksforgeeks.org",
        "expirationDate": 1681921880,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_fbp",
        "path": "/",
        "sameSite": "lax",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "fb.1.1674145838300.1958914846"
    },
    {
        "domain": ".geeksforgeeks.org",
        "expirationDate": 1708705879.874724,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GA1.2.635331085.1674145838"
    },
    {
        "domain": ".geeksforgeeks.org",
        "hostOnly": false,
        "httpOnly": true,
        "name": "authtoken",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "387b00e07a8146e02b9370f33e6802e7"
    },
    {
        "domain": ".geeksforgeeks.org",
        "expirationDate": 1705681858.339611,
        "hostOnly": false,
        "httpOnly": false,
        "name": "gfg_id5_identity",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "79ef7cc513bccd28579104bb38835f02a1f0a3f19866da4a9bfbcf891a52d71e"
    },
    {
        "domain": ".geeksforgeeks.org",
        "expirationDate": 1681921858.339454,
        "hostOnly": false,
        "httpOnly": true,
        "name": "gfguserName",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "2019ume0203%2FeyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvd3d3LmdlZWtzZm9yZ2Vla3Mub3JnXC8iLCJpYXQiOjE2NzQxNDU4NTgsImV4cCI6MTY4MTkyMTg1OCwiaGFuZGxlIjoiMjAxOXVtZTAyMDMiLCJ1dWlkIjoiY2NmNjk2NDUzZDk0ZTYzZTg4Y2Y2MGZkZGIwODRkMDQiLCJwcm9maWxlVXJsIjoiaHR0cHM6XC9cL21lZGlhLmdlZWtzZm9yZ2Vla3Mub3JnXC9pbWctcHJhY3RpY2VcL3VzZXJfd2ViLTE1OTg0MzMyMjguc3ZnIiwiaW5zdGl0dXRlSWQiOjE3NDM4LCJpbnN0aXR1dGVOYW1lIjoiSW5kaWFuIEluc3RpdHV0ZSBvZiBUZWNobm9sb2d5IEphbW11IiwibmFtZSI6IllBU0giLCJpc0ludGVyZXN0U2VsZWN0ZWQiOmZhbHNlLCJwdWlkIjoidW0rSVRkQXkxdz09IiwicGEiOjF9.rXCRvhEVzqu4gdVdgpyuyi-FzJa0h_F-fvPvv_7D1Xs1veuRiM9Xaz4LaCugg0hbT5Jud0VKr4WruddXG3QG_NhWQTIRDlPA8vGQSWPfprJ_dmrppHw-Jfb-FKbijwbZcWC31QeQPl4U1uHydUSM22_t4pgdYV0G9XGJx_dX9BQ4tmpvi9SkTJsQ_rAENNr8M2NZezxvZ97r4-8VjYhO3yfPOWAFQ1XIBTSE3nT8ItKQoRKFfLcZsOnZ8SsCqn8Tr-ICT6NuS7AKfABkcphqzo-_RCqurYHACwD7GWZ-RVUK1H5YZXIydHDUOE0hp9V5Z2br3wlcRN3CkPWQPZKncA"
    },
    {
        "domain": ".geeksforgeeks.org",
        "expirationDate": 1674232280,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_clsk",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "b3gf5d|1674145880381|3|1|g.clarity.ms/collect"
    },
    {
        "domain": ".geeksforgeeks.org",
        "expirationDate": 1705681838,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_clck",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1w9zuej|1|f8e|0"
    },
    {
        "domain": ".geeksforgeeks.org",
        "expirationDate": 1708705880.443781,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_SZ454CLTZM",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GS1.1.1674145837.1.1.1674145880.17.0.0"
    },
    {
        "domain": ".geeksforgeeks.org",
        "expirationDate": 1674145898,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gat_gtag_UA_71763465_1",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".geeksforgeeks.org",
        "expirationDate": 1681921837,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1.1.966223997.1674145837.866684987.1674145840.1674145861"
    },
    {
        "domain": ".geeksforgeeks.org",
        "expirationDate": 1674232279,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GA1.2.1722860950.1674145838"
    },
    {
        "domain": ".geeksforgeeks.org",
        "expirationDate": 1705681841.539636,
        "hostOnly": false,
        "httpOnly": true,
        "name": "gfg_nluid",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "44d3036a54091dfff730249514b1c700"
    },
    {
        "domain": ".geeksforgeeks.org",
        "hostOnly": false,
        "httpOnly": false,
        "name": "http_referrer",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "\"https://practice.geeksforgeeks.org/problem-of-the-day\""
    },
    {
        "domain": "practice.geeksforgeeks.org",
        "expirationDate": 1674232239,
        "hostOnly": true,
        "httpOnly": false,
        "name": "ln_or",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "eyIyNDM2OTcwIjoiZCJ9"
    }
]